### Feature engineering after the ETL process
create meaningful features from raw processed columns.

In [1]:
import pandas as pd
import numpy as np

In [2]:
fact_orders = pd.read_csv(
    "C:\\Users\\Steve\\Desktop\\datascience-project1\\project\\data\\processed\\fact_orders.csv",
    parse_dates=[
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ]
)


sales_fact = pd.read_csv(
    "C:\\Users\\Steve\\Desktop\\datascience-project1\\project\\data\\processed\\sales_fact.csv",
    parse_dates=[
        "shipping_limit_date",
        "order_purchase_timestamp"
    ]
)

In [3]:
print("Fact Orders Shape:", fact_orders.shape)
print("Sales Fact Shape:", sales_fact.shape)

print("\nFact Orders Columns:", len(fact_orders.columns))
print("Sales Fact Columns:", len(sales_fact.columns))

Fact Orders Shape: (99441, 22)
Sales Fact Shape: (112650, 25)

Fact Orders Columns: 22
Sales Fact Columns: 25

In [4]:
fact_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,approval_after_carrier_flag,late_delivery_flag,...,customer_zip_code_prefix,customer_city,customer_state,total_payment,payment_count,payment_type,max_installments,review_score,review_comment_title,review_comment_message
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,False,False,...,3149,sao paulo,SP,38.71,3.0,"credit_card, voucher",1.0,4.0,NaN,"Não testei o produto ainda, mas ele veio corre..."
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,False,False,...,47813,barreiras,BA,141.46,1.0,boleto,1.0,4.0,Muito boa a loja,Muito bom o produto.
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,False,False,...,75265,vianopolis,GO,179.12,1.0,credit_card,3.0,5.0,NaN,NaN
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,False,False,...,59296,sao goncalo do amarante,RN,72.20,1.0,credit_card,1.0,5.0,NaN,O produto foi exatamente o que eu esperava e e...
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,False,False,...,9195,santo andre,SP,28.62,1.0,credit_card,1.0,5.0,NaN,NaN

In [5]:
sales_fact.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,...,seller_zip_code_prefix,seller_city,seller_state,customer_id,order_purchase_timestamp,order_status,customer_state,customer_city,late_delivery_flag,review_score
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,cool_stuff,58.0,598.0,...,27277,volta redonda,SP,3ce436f183e68e07877b285a838db11a,2017-09-13 08:59:02,delivered,RJ,campos dos goytacazes,False,5.0
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,pet_shop,56.0,239.0,...,3471,sao paulo,SP,f6dd3ec061db4e3987629fe6b26e5cce,2017-04-26 10:53:06,delivered,SP,santa fe do sul,False,4.0
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,moveis_decoracao,59.0,695.0,...,37564,borda da mata,MG,6489ae5e4333f3693df5ad4372dab6d3,2018-01-14 14:33:31,delivered,MG,para de minas,False,5.0
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,perfumaria,42.0,480.0,...,14403,franca,SP,d4eb9395c8c0431ee92fce09860c5a06,2018-08-08 10:00:35,delivered,SP,atibaia,False,4.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,ferramentas_jardim,59.0,409.0,...,87900,loanda,PR,58dbd0b2d70206bf40e62cd34e84d795,2017-02-04 13:57:51,delivered,SP,varzea paulista,False,5.0

#### Date Features

The purchase timestamp contains a lot of information, but it is stored as one datetime value.

Example:

2018-08-08 08:38:49

A business analyst rarely analyses full timestamps.

Instead, we extract useful components such as:

Year
Month
Quarter
Day
Weekday
Hour

These dimensions allow us to analyse sales trends over time.

In [6]:

fact_orders["purchase_year"] = (
    fact_orders["order_purchase_timestamp"].dt.year
)

fact_orders["purchase_month"] = (
    fact_orders["order_purchase_timestamp"].dt.month
)

fact_orders["purchase_month_name"] = (
    fact_orders["order_purchase_timestamp"].dt.month_name()
)

fact_orders["purchase_quarter"] = (
    fact_orders["order_purchase_timestamp"].dt.quarter
)

fact_orders["purchase_day"] = (
    fact_orders["order_purchase_timestamp"].dt.day
)

fact_orders["purchase_weekday"] = (
    fact_orders["order_purchase_timestamp"].dt.day_name()
)

fact_orders["purchase_hour"] = (
    fact_orders["order_purchase_timestamp"].dt.hour
)

In [7]:
fact_orders[
    [
        "purchase_year",
        "purchase_month",
        "purchase_month_name",
        "purchase_quarter",
        "purchase_day",
        "purchase_weekday",
        "purchase_hour",
    ]
].head()

,purchase_year,purchase_month,purchase_month_name,purchase_quarter,purchase_day,purchase_weekday,purchase_hour
0,2017,10,October,4,2,Monday,10
1,2018,7,July,3,24,Tuesday,20
2,2018,8,August,3,8,Wednesday,8
3,2017,11,November,4,18,Saturday,19
4,2018,2,February,1,13,Tuesday,21

In [8]:

fact_orders[
    [
        "purchase_year",
        "purchase_month",
        "purchase_weekday",
        "purchase_hour",
    ]
].isna().sum()

purchase_year       0
purchase_month      0
purchase_weekday    0
purchase_hour       0
dtype: int64

### Delivery Features (Most Important)

The next section is where we'll calculate business KPIs such as:

Approval Time (hours)

Shipping Time (days)

Delivery Time (days)

Total Order Cycle (days)

Delivery Delay (days)

| Feature                   | Formula               | Business Meaning                 |
| ------------------------- | --------------------- | -------------------------------- |
| `approval_time_hours`     | Approved − Purchased  | Time taken to approve an order   |
| `shipping_time_days`      | Carrier − Approved    | Time taken to dispatch the order |
| `delivery_time_days`      | Delivered − Carrier   | Shipping duration                |
| `total_order_cycle_days`  | Delivered − Purchased | Total customer waiting time      |
| `estimated_delivery_days` | Estimated − Purchased | Promised delivery time           |
| `delivery_delay_days`     | Delivered − Estimated | Early/Late delivery              |

In [9]:
#6.1 Approval Time hours

#Measures how quickly the platform approves an order after it is placed.

fact_orders["approval_time_hours"] = (
    (
        fact_orders["order_approved_at"]
        - fact_orders["order_purchase_timestamp"]
    ).dt.total_seconds() / 3600
)

print("Approval Time Hours - NA Count:", fact_orders["approval_time_hours"].head())

Approval Time Hours - NA Count: 0     0.178333
1    30.713889
2     0.276111
3     0.298056
4     1.030556
Name: approval_time_hours, dtype: float64

In [10]:
# 3.2 Shipping Time

#Time between approval and handing the package to the shipping carrier.


fact_orders["shipping_time_days"] = (
    (
        fact_orders["order_delivered_carrier_date"]
        - fact_orders["order_approved_at"]
    ).dt.days
)

In [11]:
#Delivery Time

#Measures the time taken by the carrier to deliver the package after receiving it.

fact_orders["delivery_time_days"] = (

    (

        fact_orders["order_delivered_customer_date"]

        - fact_orders["order_delivered_carrier_date"]

    ).dt.days

)

In [12]:
fact_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,approval_after_carrier_flag,late_delivery_flag,...,purchase_year,purchase_month,purchase_month_name,purchase_quarter,purchase_day,purchase_weekday,purchase_hour,approval_time_hours,shipping_time_days,delivery_time_days
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,False,False,...,2017,10,October,4,2,Monday,10,0.178333,2.0,6.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,False,False,...,2018,7,July,3,24,Tuesday,20,30.713889,0.0,12.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,False,False,...,2018,8,August,3,8,Wednesday,8,0.276111,0.0,9.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,False,False,...,2017,11,November,4,18,Saturday,19,0.298056,3.0,9.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,False,False,...,2018,2,February,1,13,Tuesday,21,1.030556,0.0,1.0

In [13]:
#3.4 Total Order Cycle

#Measures the customer's total waiting time. From purchase until delivery.

fact_orders["total_order_cycle_days"] = (
    (
        fact_orders["order_delivered_customer_date"]
        - fact_orders["order_purchase_timestamp"]
    ).dt.days
)

In [14]:
#3.5 Estimated Delivery Time

#How many days the company promised for delivery.

fact_orders["estimated_delivery_days"] = (
    (
        fact_orders["order_estimated_delivery_date"]
        - fact_orders["order_purchase_timestamp"]
    ).dt.days
)

In [15]:
fact_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,approval_after_carrier_flag,late_delivery_flag,...,purchase_month_name,purchase_quarter,purchase_day,purchase_weekday,purchase_hour,approval_time_hours,shipping_time_days,delivery_time_days,total_order_cycle_days,estimated_delivery_days
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,False,False,...,October,4,2,Monday,10,0.178333,2.0,6.0,8.0,15
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,False,False,...,July,3,24,Tuesday,20,30.713889,0.0,12.0,13.0,19
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,False,False,...,August,3,8,Wednesday,8,0.276111,0.0,9.0,9.0,26
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,False,False,...,November,4,18,Saturday,19,0.298056,3.0,9.0,13.0,26
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,False,False,...,February,1,13,Tuesday,21,1.030556,0.0,1.0,2.0,12

In [16]:
#3.6 Delivery Delay

#Compares the actual delivery date with the estimated delivery date.

fact_orders["delivery_delay_days"] = (
    (
        fact_orders["order_delivered_customer_date"]
        - fact_orders["order_estimated_delivery_date"]
    ).dt.days
)

In [17]:
fact_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,approval_after_carrier_flag,late_delivery_flag,...,purchase_quarter,purchase_day,purchase_weekday,purchase_hour,approval_time_hours,shipping_time_days,delivery_time_days,total_order_cycle_days,estimated_delivery_days,delivery_delay_days
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,False,False,...,4,2,Monday,10,0.178333,2.0,6.0,8.0,15,-8.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,False,False,...,3,24,Tuesday,20,30.713889,0.0,12.0,13.0,19,-6.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,False,False,...,3,8,Wednesday,8,0.276111,0.0,9.0,9.0,26,-18.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,False,False,...,4,18,Saturday,19,0.298056,3.0,9.0,13.0,26,-13.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,False,False,...,1,13,Tuesday,21,1.030556,0.0,1.0,2.0,12,-10.0

Understanding the Values

Value	      Meaning

< 0	    Delivered earlier than promised

0	    Delivered exactly on time

#### > 0   	Delivered late

In [18]:
delivery_features = [
    "approval_time_hours",
    "shipping_time_days",
    "delivery_time_days",
    "total_order_cycle_days",
    "estimated_delivery_days",
    "delivery_delay_days",
]

fact_orders[delivery_features].describe()

,approval_time_hours,shipping_time_days,delivery_time_days,total_order_cycle_days,estimated_delivery_days,delivery_delay_days
count,99281.000000,97644.000000,96475.000000,96476.000000,99441.000000,96476.000000
mean,10.419094,2.301749,8.878310,12.094086,23.403958,-11.876881
std,26.038004,3.560283,8.746088,9.551746,8.829562,10.183854
min,0.000000,-172.000000,-17.000000,0.000000,1.000000,-147.000000
25%,0.215000,0.000000,4.000000,6.000000,18.000000,-17.000000
50%,0.343333,1.000000,7.000000,10.000000,23.000000,-12.000000
75%,14.580833,3.000000,12.000000,15.000000,28.000000,-7.000000
max,4509.180556,125.000000,205.000000,209.000000,155.000000,188.000000

In [19]:
fact_orders[
    [
        "approval_time_hours",
        "shipping_time_days",
        "delivery_time_days",
        "total_order_cycle_days",
    ]
].min()

approval_time_hours         0.0
shipping_time_days       -172.0
delivery_time_days        -17.0
total_order_cycle_days      0.0
dtype: float64

In [20]:
fact_orders[
    fact_orders["shipping_time_days"] < 0
][[
    "order_id",
    "order_approved_at",
    "order_delivered_carrier_date",
    "shipping_time_days"
]].head(10)

,order_id,order_approved_at,order_delivered_carrier_date,shipping_time_days
15,dcb36b511fcac050b97cd5c05de84dc3,2018-06-12 23:31:02,2018-06-11 14:54:00,-2.0
64,688052146432ef8253587b930b01a06d,2018-04-24 18:25:22,2018-04-23 19:19:14,-1.0
199,58d4c4747ee059eeeb865b349b41f53a,2018-07-26 23:31:53,2018-07-24 12:57:00,-3.0
210,412fccb2b44a99b36714bca3fef8ad7b,2018-07-23 12:31:53,2018-07-23 12:24:00,-1.0
415,56a4ac10a4a8f2ba7693523bb439eede,2018-07-27 23:31:09,2018-07-24 14:03:00,-4.0
481,32e4fa9bb468884309b58b9348de70c3,2018-07-05 16:33:06,2018-07-05 14:50:00,-1.0
483,4df92d82d79c3b52c7138679fa9b07fc,2018-07-29 23:30:52,2018-07-26 14:46:00,-4.0
585,16e38caa92e342c7780f68832f832d4d,2018-05-07 16:52:39,2018-05-07 15:09:00,-1.0
615,b9afddbdcfadc9a87b41a83271c3e888,2018-08-16 14:05:13,2018-08-16 13:27:00,-1.0
817,6051e6d3da9a50b7325cbe9c81025062,2018-07-05 16:31:26,2018-07-04 12:14:00,-2.0

In [21]:
fact_orders[ fact_orders["delivery_time_days"] < 0][[
    "order_id",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "delivery_time_days"]].head(10)

,order_id,order_delivered_carrier_date,order_delivered_customer_date,delivery_time_days
6437,a1abeb653a4d4cd1e142ccb8c82cd069,2017-07-28 16:57:58,2017-07-25 19:32:56,-3.0
9553,383aa8b2724fe452d9ccd9934a8c628b,2017-07-07 17:22:41,2017-07-06 14:27:51,-2.0
13487,cb1134f9010d242e9515ad1c78ec0c39,2017-07-20 19:22:02,2017-07-19 14:13:28,-2.0
14474,dceb62e8fa94b46006c9554fed743df0,2017-08-01 18:23:30,2017-07-26 18:09:10,-7.0
19268,5f9d46795c3126674e52becb3a1a517f,2017-07-20 23:03:42,2017-07-20 18:52:41,-1.0
21338,8c78d01de3a9009e23d6877a7cc9be20,2016-10-26 11:41:53,2016-10-25 17:51:46,-1.0
22520,b27af682321527a6349f1761eb3f360c,2017-06-27 14:51:54,2017-06-26 15:45:35,-1.0
25393,1cc3ae63caffff2d6c3ee3e78e074acf,2017-08-10 18:28:56,2017-08-10 18:05:38,-1.0
25646,e37f11cae9985ca58f0b56f268720537,2017-08-01 18:17:47,2017-07-31 17:49:56,-2.0
27470,fa3e37584f4fdb1ded0e0de700dfcb4e,2017-08-09 18:18:43,2017-08-01 21:13:01,-8.0

In [22]:
fact_orders["shipping_time_days"] = (
    fact_orders["shipping_time_days"]
    .mask(fact_orders["shipping_time_days"] < 0)
)

fact_orders["delivery_time_days"] = (
    fact_orders["delivery_time_days"]
    .mask(fact_orders["delivery_time_days"] < 0)
)

In [23]:
fact_orders[
    [
        "shipping_time_days",
        "delivery_time_days"
    ]
].min()

shipping_time_days    0.0
delivery_time_days    0.0
dtype: float64

In [24]:
print("Negative Shipping Times:",
      fact_orders["shipping_time_days"].isna().sum())

print("Negative Delivery Times:",
      fact_orders["delivery_time_days"].isna().sum())

Negative Shipping Times: 3156
Negative Delivery Times: 2989

In [25]:
print(f"Shipping anomalies: {fact_orders['shipping_time_days'].isna().mean()*100:.2f}%")

print(f"Delivery anomalies: {fact_orders['delivery_time_days'].isna().mean()*100:.2f}%")

Shipping anomalies: 3.17%
Delivery anomalies: 3.01%

In [26]:
fact_orders[
    [
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
    ]
].head()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [27]:
fact_orders[
    [
        "shipping_time_days",
        "delivery_time_days",
        "delivery_delay_days"
    ]
].describe()

       shipping_time_days  delivery_time_days  delivery_delay_days
count        96285.000000        96452.000000         96476.000000
mean             2.359090            8.881330           -11.876881
std              3.506244            8.744759            10.183854
min              0.000000            0.000000          -147.000000
25%              0.000000            4.000000           -17.000000
50%              1.000000            7.000000           -12.000000
75%              3.000000           12.000000            -7.000000
max            125.000000          205.000000           188.000000

In [28]:
fact_orders["shipping_time_days"].value_counts().sort_index().head(15)

shipping_time_days
0.0     28090
1.0     23110
2.0     14317
3.0     10214
4.0      6374
5.0      4429
6.0      3098
7.0      1626
8.0       911
9.0       691
10.0      611
11.0      429
12.0      365
13.0      383
14.0      298
Name: count, dtype: int64

In [29]:
fact_orders["delivery_time_days"].value_counts().sort_index().head(15)

delivery_time_days
0.0     2684
1.0     7881
2.0     5452
3.0     6892
4.0     6538
5.0     7875
6.0     9056
7.0     8546
8.0     5699
9.0     4284
10.0    3790
11.0    3451
12.0    3161
13.0    3283
14.0    2803
Name: count, dtype: int64

In [30]:
fact_orders["shipping_time_days"] = fact_orders["shipping_time_days"].mask(
    fact_orders["shipping_time_days"] < 0
)

fact_orders["delivery_time_days"] = fact_orders["delivery_time_days"].mask(
    fact_orders["delivery_time_days"] < 0
)

In [31]:
fact_orders.shape

(99441, 35)

In [32]:
fact_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,approval_after_carrier_flag,late_delivery_flag,...,purchase_quarter,purchase_day,purchase_weekday,purchase_hour,approval_time_hours,shipping_time_days,delivery_time_days,total_order_cycle_days,estimated_delivery_days,delivery_delay_days
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,False,False,...,4,2,Monday,10,0.178333,2.0,6.0,8.0,15,-8.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,False,False,...,3,24,Tuesday,20,30.713889,0.0,12.0,13.0,19,-6.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,False,False,...,3,8,Wednesday,8,0.276111,0.0,9.0,9.0,26,-18.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,False,False,...,4,18,Saturday,19,0.298056,3.0,9.0,13.0,26,-13.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,False,False,...,1,13,Tuesday,21,1.030556,0.0,1.0,2.0,12,-10.0

### Payment features

#### 1. Average Payment Per Installment

In [33]:
fact_orders["avg_payment_per_installment"] = (
    fact_orders["total_payment"] /
    fact_orders["max_installments"]
)
#This measures the average amount paid in each installment.

In [34]:
#2. Multiple Payment Methods Flag

#Some orders use more than one payment method (for example, credit card + voucher).

fact_orders["multiple_payment_methods"] = (
    fact_orders["payment_count"] > 1
)

In [35]:
fact_orders.shape

(99441, 37)

In [36]:
fact_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,approval_after_carrier_flag,late_delivery_flag,...,purchase_weekday,purchase_hour,approval_time_hours,shipping_time_days,delivery_time_days,total_order_cycle_days,estimated_delivery_days,delivery_delay_days,avg_payment_per_installment,multiple_payment_methods
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,False,False,...,Monday,10,0.178333,2.0,6.0,8.0,15,-8.0,38.710000,True
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,False,False,...,Tuesday,20,30.713889,0.0,12.0,13.0,19,-6.0,141.460000,False
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,False,False,...,Wednesday,8,0.276111,0.0,9.0,9.0,26,-18.0,59.706667,False
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,False,False,...,Saturday,19,0.298056,3.0,9.0,13.0,26,-13.0,72.200000,False
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,False,False,...,Tuesday,21,1.030556,0.0,1.0,2.0,12,-10.0,28.620000,False

## Reviews and Rating

In [37]:
# 5.1 High Rating Flag Marks orders with a review score of 4 or 5 as positive customer experiences.

fact_orders["high_rating"] = (
    fact_orders["review_score"] >= 4
)

In [38]:
#5.2 Low Rating Flag Marks orders with a review score of 1 or 2.

#These are generally dissatisfied customers.

fact_orders["low_rating"] = (
    fact_orders["review_score"] <= 2
)

In [39]:
fact_orders.shape

(99441, 39)

In [40]:
fact_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,approval_after_carrier_flag,late_delivery_flag,...,approval_time_hours,shipping_time_days,delivery_time_days,total_order_cycle_days,estimated_delivery_days,delivery_delay_days,avg_payment_per_installment,multiple_payment_methods,high_rating,low_rating
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,False,False,...,0.178333,2.0,6.0,8.0,15,-8.0,38.710000,True,True,False
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,False,False,...,30.713889,0.0,12.0,13.0,19,-6.0,141.460000,False,True,False
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,False,False,...,0.276111,0.0,9.0,9.0,26,-18.0,59.706667,False,True,False
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,False,False,...,0.298056,3.0,9.0,13.0,26,-13.0,72.200000,False,True,False
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,False,False,...,1.030556,0.0,1.0,2.0,12,-10.0,28.620000,False,True,False

In [41]:
fact_orders[
    [
        "review_score",
        "high_rating",
        "low_rating"
    ]
].head(10)

   review_score  high_rating  low_rating
0           4.0         True       False
1           4.0         True       False
2           5.0         True       False
3           5.0         True       False
4           5.0         True       False
5           4.0         True       False
6           2.0        False        True
7           5.0         True       False
8           1.0        False        True
9           5.0         True       False

In [42]:
print("High Ratings:")
print(fact_orders["high_rating"].value_counts())

print("\nLow Ratings:")
print(fact_orders["low_rating"].value_counts())

High Ratings:
high_rating
True     76046
False    23395
Name: count, dtype: int64

Low Ratings:
low_rating
False    84947
True     14494
Name: count, dtype: int64

## ORDER SALES NEW FEATURES

In [43]:
#Delivered Order Flag

#Indicates whether an order was successfully delivered.

fact_orders["is_delivered"] = (
    fact_orders["order_status"] == "delivered"
)

In [44]:
# 6.2 Cancelled Order Flag

# Identifies cancelled orders.

fact_orders["is_cancelled"] = (

    fact_orders["order_status"] == "canceled"

)

6.3 In Progress Flag

Orders that are not yet completed.

This includes:

processing
shipped
invoiced
approved
created

In [45]:
fact_orders["is_in_progress"] = (
    ~fact_orders["order_status"].isin(
        ["delivered", "canceled"]
    )
)

In [46]:
fact_orders[
    [
        "order_status",
        "is_delivered",
        "is_cancelled",
        "is_in_progress",
    ]
].head(10)

  order_status  is_delivered  is_cancelled  is_in_progress
0    delivered          True         False           False
1    delivered          True         False           False
2    delivered          True         False           False
3    delivered          True         False           False
4    delivered          True         False           False
5    delivered          True         False           False
6     invoiced         False         False            True
7    delivered          True         False           False
8    delivered          True         False           False
9    delivered          True         False           False

In [47]:
print("Delivered Orders")
print(fact_orders["is_delivered"].value_counts())

print("\nCancelled Orders")
print(fact_orders["is_cancelled"].value_counts())

print("\nIn Progress Orders")
print(fact_orders["is_in_progress"].value_counts())

Delivered Orders
is_delivered
True     96478
False     2963
Name: count, dtype: int64

Cancelled Orders
is_cancelled
False    98816
True       625
Name: count, dtype: int64

In Progress Orders
is_in_progress
False    97103
True      2338
Name: count, dtype: int64

### 7. Sales Fact Features

Unlike fact_orders, sales_fact is at the product level (1 row = 1 product sold). Here we'll create features related to revenue, freight, and product characteristics.

7.1 Total Item Value


The customer pays:

Product Price
Shipping (Freight)

The total value of one item is:

Price + Freight

In [48]:

sales_fact["total_item_value"] = (
    sales_fact["price"] +
    sales_fact["freight_value"]
)

### 7.2 Freight Percentage
### Measures how much of the item's value comes from shipping.

In [49]:
sales_fact["freight_percentage"] = (
    sales_fact["freight_value"] /
    sales_fact["price"]
) * 100

### 7.3 Heavy Product Flag


Products above the dataset's median weight are marked as heavy.
Using the median is better than choosing an arbitrary threshold because it adapts to the dataset.

In [50]:
median_weight = sales_fact["product_weight_g"].median()

sales_fact["is_heavy_product"] = (
    sales_fact["product_weight_g"] >
    median_weight
)

### 7.4 Large Product Flag

We'll estimate a product's package volume.

Formula:

Length × Width × Height

In [51]:


sales_fact["product_volume_cm3"] = (
    sales_fact["product_length_cm"] *
    sales_fact["product_width_cm"] *
    sales_fact["product_height_cm"]
)

In [52]:
median_volume = sales_fact["product_volume_cm3"].median()

sales_fact["is_large_product"] = (
    sales_fact["product_volume_cm3"] >
    median_volume
)

### 7.5 High Freight Cost Flag

Some products have unusually high shipping costs.

We'll identify them using the 75th percentile (top 25% of freight costs).

In [53]:

freight_threshold = sales_fact["freight_value"].quantile(0.75)

sales_fact["high_freight"] = (
    sales_fact["freight_value"] >
    freight_threshold
)

In [56]:
sales_fact[
    [
        "price",
        "freight_value",
        "total_item_value",
        "freight_percentage",
        "product_volume_cm3",
        "is_heavy_product",
        "is_large_product",
        "high_freight",
    ]
].head()

,price,freight_value,total_item_value,freight_percentage,product_volume_cm3,is_heavy_product,is_large_product,high_freight
0,58.90,13.29,72.19,22.563667,3528.0,False,False,False
1,239.90,19.93,259.83,8.307628,60000.0,True,True,False
2,199.00,17.87,216.87,8.979899,14157.0,True,True,False
3,12.99,12.79,25.78,98.460354,2400.0,False,False,False
4,199.90,18.14,218.04,9.074537,42000.0,True,True,False

In [57]:
sales_fact[
    [
        "total_item_value",
        "freight_percentage",
        "product_volume_cm3",
    ]
].describe()

       total_item_value  freight_percentage  product_volume_cm3
count     112650.000000       112650.000000       112632.000000
mean         140.644059           32.086355        15243.709567
std          190.724394           34.989368        23418.524686
min            6.080000            0.000000          168.000000
25%           55.220000           13.403366         2851.500000
50%           92.320000           23.135624         6480.000000
75%          157.937500           39.303621        18375.000000
max         6929.310000         2623.529412       296208.000000

### Final Verdict validation Checkup before EDA

In [58]:
print("FACT ORDERS")
print(fact_orders.shape)

print("\nSALES FACT")
print(sales_fact.shape)

FACT ORDERS
(99441, 42)

SALES FACT
(112650, 31)

In [62]:
# check the fact-orders duplicates.
print(
    "Duplicate Orders:",
    fact_orders["order_id"].duplicated().sum()
)

Duplicate Orders: 0

In [63]:
# check the sales-fact duplicates.
print(
    "Duplicate Order Items:",
    sales_fact[
        ["order_id", "order_item_id"]
    ].duplicated().sum()
)

Duplicate Order Items: 0

In [64]:
# check missing values 
missing_fact = (
    fact_orders.isna()
    .sum()
    .sort_values(ascending=False)
)

missing_sales = (
    sales_fact.isna()
    .sum()
    .sort_values(ascending=False)
)

print(missing_fact.head(15))

print("\n")

print(missing_sales.head(15))

review_comment_title             87891
review_comment_message           58666
shipping_time_days                3156
delivery_time_days                2989
total_order_cycle_days            2965
delivery_delay_days               2965
order_delivered_customer_date     2965
order_delivered_carrier_date      1783
review_score                       768
order_approved_at                  160
approval_time_hours                160
max_installments                     1
avg_payment_per_installment          1
payment_type                         1
total_payment                        1
dtype: int64


product_description_lenght    1603
product_name_lenght           1603
product_category_name         1603
product_photos_qty            1603
review_score                   942
product_length_cm               18
product_height_cm               18
product_width_cm                18
product_weight_g                18
product_volume_cm3              18
freight_value                    0
product_id                       0
order_item_id                    0
shipping_limit_date              0
price                            0
dtype: int64

In [65]:
print(fact_orders.dtypes)

print("\n")

print(sales_fact.dtypes)

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
approval_after_carrier_flag                bool
late_delivery_flag                         bool
delivery_before_carrier_flag               bool
customer_unique_id                          str
customer_zip_code_prefix                  int64
customer_city                               str
customer_state                              str
total_payment                           float64
payment_count                           float64
payment_type                                str
max_installments                        float64
review_score                            float64
review_comment_title                        str
review_comment_message                      str
purchase_year                             int32
purchase_month                            int32
purchase_month_name                         str
purchase_quarter                          int32
purchase_day                              int32
purchase_weekday                            str
purchase_hour                             int32
approval_time_hours                     float64
shipping_time_days                      float64
delivery_time_days                      float64
total_order_cycle_days                  float64
estimated_delivery_days                   int64
delivery_delay_days                     float64
avg_payment_per_installment             float64
multiple_payment_methods                   bool
high_rating                                bool
low_rating                                 bool
is_delivered                               bool
is_cancelled                               bool
is_in_progress                             bool
dtype: object


order_id                                 str
order_item_id                          int64
product_id                               str
seller_id                                str
shipping_limit_date           datetime64[us]
price                                float64
freight_value                        float64
product_category_name                    str
product_name_lenght                  float64
product_description_lenght           float64
product_photos_qty                   float64
product_weight_g                     float64
product_length_cm                    float64
product_height_cm                    float64
product_width_cm                     float64
seller_zip_code_prefix                 int64
seller_city                              str
seller_state                             str
customer_id                              str
order_purchase_timestamp      datetime64[us]
order_status                             str
customer_state                           str
customer_city                            str
late_delivery_flag                      bool
review_score                         float64
total_item_value                     float64
freight_percentage                   float64
is_heavy_product                        bool
product_volume_cm3                   float64
is_large_product                        bool
high_freight                            bool
dtype: object

In [66]:
# check the delivery KPIS
delivery_cols = [
    "approval_time_hours",
    "shipping_time_days",
    "delivery_time_days",
    "total_order_cycle_days",
    "estimated_delivery_days",
    "delivery_delay_days",
]

fact_orders[delivery_cols].describe()

,approval_time_hours,shipping_time_days,delivery_time_days,total_order_cycle_days,estimated_delivery_days,delivery_delay_days
count,99281.000000,96285.000000,96452.000000,96476.000000,99441.000000,96476.000000
mean,10.419094,2.359090,8.881330,12.094086,23.403958,-11.876881
std,26.038004,3.506244,8.744759,9.551746,8.829562,10.183854
min,0.000000,0.000000,0.000000,0.000000,1.000000,-147.000000
25%,0.215000,0.000000,4.000000,6.000000,18.000000,-17.000000
50%,0.343333,1.000000,7.000000,10.000000,23.000000,-12.000000
75%,14.580833,3.000000,12.000000,15.000000,28.000000,-7.000000
max,4509.180556,125.000000,205.000000,209.000000,155.000000,188.000000

In [67]:
#6. Review Features
print(fact_orders["high_rating"].value_counts())

print()

print(fact_orders["low_rating"].value_counts())

high_rating
True     76046
False    23395
Name: count, dtype: int64

low_rating
False    84947
True     14494
Name: count, dtype: int64

In [72]:
### CHECK FOR ORDERS WITH MAX INSTALLMENTS = 0 WRITE A IF > O DO AVERAGE ELSE NAN

fact_orders[
    fact_orders["max_installments"] == 0
][[
    "order_id",
    "total_payment",
    "payment_count",
    "max_installments"
]].head(20)

,order_id,total_payment,payment_count,max_installments
63782,744bade1fcf9ff3f31d860ace076d422,58.69,1.0,0.0
66368,1a57108394169c0b47d8f876acc9ba2d,129.94,1.0,0.0

In [73]:
print(
    "Zero Installments:",
    (fact_orders["max_installments"] == 0).sum()
)

Zero Installments: 2

In [74]:
import numpy as np

fact_orders["avg_payment_per_installment"] = np.where(
    fact_orders["max_installments"] > 0,
    fact_orders["total_payment"] / fact_orders["max_installments"],
    np.nan
)

In [76]:
## 7. Check for orders with max_installments = 0 and calculate average payment per installment if max_installments > 0, else set to NaN.
fact_orders[
    [
        "total_payment",
        "payment_count",
        "max_installments",
        "avg_payment_per_installment",
    ]
].describe()

,total_payment,payment_count,max_installments,avg_payment_per_installment
count,99440.000000,99440.000000,99440.000000,99438.000000
mean,160.990267,1.044710,2.930521,82.656236
std,221.951257,0.381166,2.715685,137.376198
min,0.000000,1.000000,0.000000,0.000000
25%,62.010000,1.000000,1.000000,28.602083
50%,105.290000,1.000000,2.000000,53.650833
75%,176.970000,1.000000,4.000000,93.300000
max,13664.080000,29.000000,24.000000,13664.080000

### 8. Sales Features

Verify:

No negative prices

No negative freight

Product volume > 0 for most products

In [77]:

sales_fact[
    [
        "price",
        "freight_value",
        "total_item_value",
        "freight_percentage",
        "product_volume_cm3",
    ]
].describe()

,price,freight_value,total_item_value,freight_percentage,product_volume_cm3
count,112650.000000,112650.000000,112650.000000,112650.000000,112632.000000
mean,120.653739,19.990320,140.644059,32.086355,15243.709567
std,183.633928,15.806405,190.724394,34.989368,23418.524686
min,0.850000,0.000000,6.080000,0.000000,168.000000
25%,39.900000,13.080000,55.220000,13.403366,2851.500000
50%,74.990000,16.260000,92.320000,23.135624,6480.000000
75%,134.900000,21.150000,157.937500,39.303621,18375.000000
max,6735.000000,409.680000,6929.310000,2623.529412,296208.000000

## 9. Final Engineered Columns check

In [78]:
engineered_fact = [
    "purchase_year",
    "purchase_month",
    "purchase_month_name",
    "purchase_quarter",
    "purchase_day",
    "purchase_weekday",
    "purchase_hour",
    "approval_time_hours",
    "shipping_time_days",
    "delivery_time_days",
    "total_order_cycle_days",
    "estimated_delivery_days",
    "delivery_delay_days",
    "avg_payment_per_installment",
    "multiple_payment_methods",
    "high_rating",
    "low_rating",
    "is_delivered",
    "is_cancelled",
    "is_in_progress",
]

print(
    set(engineered_fact).issubset(
        fact_orders.columns
    )
)

True

In [79]:
engineered_sales = [
    "total_item_value",
    "freight_percentage",
    "product_volume_cm3",
    "is_heavy_product",
    "is_large_product",
    "high_freight",
]

print(
    set(engineered_sales).issubset(
        sales_fact.columns
    )
)

True

In [80]:
# 10. Export Final Datasets


import os

os.makedirs("feature_engineered", exist_ok=True)

fact_orders.to_csv(
    "C:\\Users\\Steve\\Desktop\\datascience-project1\\project\\data\\processed\\final_processed_datasets\\fact_orders_fe.csv",
    index=False
)

sales_fact.to_csv(
    "C:\\Users\\Steve\\Desktop\\datascience-project1\\project\\data\\processed\\final_processed_datasets\\sales_fact_fe.csv",
    index=False
)